### ISSUE TITLE
6.1.8_4安装后运行时闪闪闪退

### ISSUE THREAD

**Issue by lnxcyq** [wangwang-code/AutoX#13]
手机是VIVO，安卓10

**Comment by ghost** [comment]
已修正，并尝试提升性能及流畅度（欢迎测试反馈问题）：[项目重构，优化编译设置，尝试升级编译组件以增强APP性能及流畅度](https://github.com/wangwang-code/AutoX/pull/12) @wangwang-code

**Comment by lnxcyq** [comment]
删除后重新安装你提供的最新apk，安装后还是闪退耶

**Comment by ghost** [comment]
> 删除后重新安装你提供的最新apk，安装后还是闪退耶

@lnxcyq  当然闪退啦，因为 @wangwang-code 这时连PR都还没有合并，哪里有更新的apk呢？
@wangwang-code 这边先帮你删除掉闪退的版本，合并PR以节省云编译时间，如果有什么不对，你再修改。

**Comment by wangwang-code** [comment]
> > 删除后重新安装你提供的最新apk，安装后还是闪退耶
> 
> @lnxcyq 当然闪退啦，因为 @wangwang-code 这时连PR都还没有合并，哪里有更新的apk呢？ @wangwang-code 这边先帮你删除掉闪退的版本，合并PR以节省云编译时间，如果有什么不对，你再修改。

@LZX284 别改控制台啊，我故意砍掉输入框，弄小标题栏的

**Comment by ghost** [comment]
> @LZX284 别改控制台啊，我故意砍掉输入框，弄小标题栏的

@wangwang-code 不好意思，当时为了确认问题回退了不少代码，后面就忘记把你的控制台补回去了。要不你自己再修改一下？

**Comment by wangwang-code** [comment]
> > @LZX284 别改控制台啊，我故意砍掉输入框，弄小标题栏的
> 
> @wangwang-code 不好意思，当时为了确认问题回退了不少代码，后面就忘记把你的控制台补回去了。要不你自己再修改一下？

已经改了，另外，@wilinz 已经弄赞助了，你也弄一个?

**Comment by ghost** [comment]
> 已经改了，另外，@wilinz 已经弄赞助了，你也弄一个?

有赞助的话，这个项目的状况应该会好不少。不过自己不是专业搞这个的，以后时间也没那么充裕，还是随缘吧。

**Comment by wangwang-code** [comment]
> > 已经改了，另外，@wilinz 已经弄赞助了，你也弄一个?
> 
> 有赞助的话，这个项目的状况应该会好不少。不过自己不是专业搞这个的，以后时间也没那么充裕，还是随缘吧。

总不能白费精力

**Comment by wangwang-code** [comment]
@LZX284 快要编译好了，感觉速度没快多少

难怪gradle有人叫它乌龟

**Comment by ghost** [comment]
> @LZX284 快要编译好了，感觉速度没快多少

编译主要吃CPU性能。这次升级Android SDK 和 Java 版本改善的主要是APP的运行时性能，和编译速度也没关系吧？

**Comment by wangwang-code** [comment]
> > @LZX284 快要编译好了，感觉速度没快多少
> 
> 编译主要吃CPU性能。这次升级Android SDK 和 Java 版本改善的主要是APP的运行时性能，和编译速度也没关系吧？

阿巴阿巴

**Comment by wilinz** [comment]
我8核16线程编译都要4分钟，主要是github云编译的vps性能不怎么样

**Comment by wilinz** [comment]
gradle确实是乌龟

**Comment by wangwang-code** [comment]
> 我8核16线程编译都要4分钟，主要是github云编译的vps性能不怎么样

主要云编译没有缓存

**Comment by wilinz** [comment]
国外从阿里云下依赖也挺慢

**Comment by wangwang-code** [comment]
> 国外从阿里云下依赖也挺慢

麻麻咪哦

**Comment by wangwang-code** [comment]
@LZX284 https://github.com/wangwang-code/AutoX/releases/tag/6.1.8t_4 去世，不读文件，但文件夹正常

**Comment by wangwang-code** [comment]
开所有文件访问权限才正常

但给这个权限，创建的文件又会。失踪

**Comment by wangwang-code** [comment]
> 开所有文件访问权限才正常
> 
> 但给这个权限，创建的文件又会。失踪

找到问题了，存储只授予了媒体的访问权限

**Comment by wangwang-code** [comment]
> > 开所有文件访问权限才正常
> > 但给这个权限，创建的文件又会。失踪
> 
> 找到问题了，存储只授予了媒体的访问权限

但一给"允许管理所有文件" "所有文件访问权限" 也会跟着被授权，导致创建又失踪了

**Comment by wangwang-code** [comment]
@LZX284 升级升出BUG了，以前申请的存储权限里只有禁用和允许管理所有文件，升级后多了个媒体文件，现在要么适配，要么回滚

**Comment by ghost** [comment]
> @LZX284 升级升出BUG了，以前申请的存储权限里只有禁用和允许管理所有文件，升级后多了个媒体文件，现在要么适配，要么回滚

@wangwang-code 这个权限是在Android11(API 30)后才有的，把 [build.gradle](https://github.com/wangwang-code/AutoX/edit/dev-test/build.gradle) 中的 target 值 改为 29 试试

**Comment by wangwang-code** [comment]
> > @LZX284 升级升出BUG了，以前申请的存储权限里只有禁用和允许管理所有文件，升级后多了个媒体文件，现在要么适配，要么回滚
> 
> @wangwang-code 这个权限是在Android11(API 30)后才有的，把 [build.gradle](https://github.com/wangwang-code/AutoX/edit/dev-test/build.gradle) 中的 target 值 改为 29 试试

在编译了

**Comment by wangwang-code** [comment]
@LZX284 正常的，不过，OCR耗时有点高 以前都是500ms左右 现在1600ms 蛮怪的

**Comment by ghost** [comment]
> @LZX284 正常的，不过，OCR耗时有点高 以前都是500ms左右 现在1600ms 蛮怪的

因为加了校验功能识别就会慢点，但稳定性更高。不过现在V3版模型的OCR都出来了，你想试试吗？

**Comment by wangwang-code** [comment]
> > @LZX284 正常的，不过，OCR耗时有点高 以前都是500ms左右 现在1600ms 蛮怪的
> 
> 因为加了校验功能识别就会慢点，但稳定性更高。不过现在V3版模型的OCR也出来了，你想试试吗？

逝世吧，不过能只换模型就好，代码，····

**Comment by ghost** [comment]
> 逝世吧，不过能只换模型就好，代码，····

代码不需要你操心，有现成的已经集成到auto.js里的：[TonyJiangWJ/Auto.js](https://github.com/TonyJiangWJ/Auto.js)

**Comment by wangwang-code** [comment]
看了下，没目前v3，没有出移动端的专们的优化

**Comment by wangwang-code** [comment]
这个issues该关了，偏了

**Comment by wangwang-code** [comment]
不要问为啥又打开了，当我连接电脑时，它崩溃了

@LZX284

**Comment by wangwang-code** [comment]
> 不要问为啥又打开了，当我连接电脑时，它崩溃了
> 
> @LZX284

Version: 618
Android: 30
java.lang.SecurityException: getDeviceId: The user 10711 does not meet the requirements to access device identifiers.
android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
android.os.Parcel.createException(Parcel.java:2371)
android.os.Parcel.readException(Parcel.java:2354)
android.os.Parcel.readException(Parcel.java:2296)
com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:11513)
android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1966)
org.autojs.autojs.ui.main.drawer.DrawerFragment.getIMEI(DrawerFragment.java:388)
org.autojs.autojs.ui.main.drawer.DrawerFragment.inputRemoteHost(DrawerFragment.java:408)
org.autojs.autojs.ui.main.drawer.DrawerFragment.connectOrDisconnectToRemote(DrawerFragment.java:331)
org.autojs.autojs.ui.main.drawer.DrawerFragment$$ExternalSyntheticLambda7.onClick(Unknown Source:2)
org.autojs.autojs.ui.main.drawer.DrawerMenuItem.performAction(DrawerMenuItem.java:87)
org.autojs.autojs.ui.main.drawer.DrawerMenuItemViewHolder.onClick(DrawerMenuItemViewHolder.java:105)
org.autojs.autojs.ui.main.drawer.DrawerMenuItemViewHolder.lambda$new$0(DrawerMenuItemViewHolder.java:51)
org.autojs.autojs.ui.main.drawer.DrawerMenuItemViewHolder.$r8$lambda$717pOEieSmZnJ4s0iPeWP3oPLcU(Unknown Source:0)
org.autojs.autojs.ui.main.drawer.DrawerMenuItemViewHolder$$ExternalSyntheticLambda1.onCheckedChanged(Unknown Source:2)
org.autojs.autojs.ui.widget.SwitchCompat.lambda$setOnCheckedChangeListener$0(SwitchCompat.java:33)
org.autojs.autojs.ui.widget.SwitchCompat.$r8$lambda$nacNQraJPQOaBd-PLsrSsSXIvVY(Unknown Source:0)
org.autojs.autojs.ui.widget.SwitchCompat$$ExternalSyntheticLambda0.onCheckedChanged(Unknown Source:4)
android.widget.CompoundButton.setChecked(CompoundButton.java:218)
androidx.appcompat.widget.SwitchCompat.setChecked(SwitchCompat.java:1162)
org.autojs.autojs.ui.widget.PrefSwitch.setChecked(PrefSwitch.java:89)
androidx.appcompat.widget.SwitchCompat.toggle(SwitchCompat.java:1157)
android.widget.CompoundButton.performClick(CompoundButton.java:142)
android.view.View.performClickInternal(View.java:7477)
android.view.View.access$3600(View.java:824)
android.view.View$PerformClick.run(View.java:28702)
android.os.Handler.handleCallback(Handler.java:938)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:257)
android.app.ActivityThread.main(ActivityThread.java:8284)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1031)

**Comment by ghost** [comment]
> 不要问为啥又打开了，当我连接电脑时，它崩溃了

@wangwang-code 谷歌一下异常内容大概就知道是什么错误了。这个是Android 10（API 级别 29）加入的设备标识符限制，看来又又又得回退了，target 改成 28 应该可以，不过难免还有其它问题，不行就还是退回 26 吧……

**Comment by wilinz** [comment]
target 没事还是不要升，太难适配了（需要改的地方太多了）

**Comment by wangwang-code** [comment]
> > 不要问为啥又打开了，当我连接电脑时，它崩溃了
> 
> @wangwang-code 谷歌一下异常内容大概就知道是什么错误了。这个是Android 10（API 级别 29）加入的设备标识符限制，看来又又又得回退了，target 改成 28 应该可以，不过难免还有其它问题，不行就还是退回 26 吧……

26仍然闪退，报错一样

**Comment by ghost** [comment]
> target 没事还是不要升，太难适配了（需要改的地方太多了）

感觉升级确实麻烦，但不升的话不知道会不会影响对新设备的兼容性？

**Comment by ghost** [comment]
> 26仍然闪退，报错一样

@wangwang-code  尝试修复了一下，看看行不行

**Comment by wilinz** [comment]
> > target 没事还是不要升，太难适配了（需要改的地方太多了）
> 
> 感觉升级确实麻烦，但不升的话不知道会不会影响对新设备的兼容性？

不崩溃就是最好的兼容

**Comment by ghost** [comment]
> 不崩溃就是最好的兼容

@wilinz  你可以看看这里的issue：[hamibot](https://github.com/hamibot/hamibot) 
其中多数bug，现在的AutoX 已经修复，单论APP本身 hamibot 差的有点多，但 现在的 hamibot 发展状况算起来其实是强于 AutoX的，知名度、活跃度、用户量等也不是AutoX能比的。

**Comment by ghost** [comment]
@wilinz  再看看这些：
[脚本市场](https://hamibot.cn/marketplace/category/free-trials)  
[auto.js热门脚本](https://github.com/dundunnp/auto_xuexiqiangguo/issues)
除了APP本身不崩溃，脚本的兼容性应该也是很重要的……

**Comment by wilinz** [comment]
有时间慢慢来，目前维护者太少

**Comment by ghost** [comment]
> 有时间慢慢来，目前维护者太少

@wilinz  那你认为目前的AutoX能够吸引更多开发者参与维护吗？或者说，这个项目对于开发者的吸引力在哪里？

**Comment by wangwang-code** [comment]
> > 有时间慢慢来，目前维护者太少
> 
> @wilinz 那你认为目前的AutoX能够吸引更多开发者参与维护吗？或者说，这个项目对于开发者的吸引力在哪里？

其实，我就是从hamibot转过来的，至于原因嘛…

**Comment by wilinz** [comment]
> > 有时间慢慢来，目前维护者太少
> 
> @wilinz 那你认为目前的AutoX能够吸引更多开发者参与维护吗？或者说，这个项目对于开发者的吸引力在哪里？

首先是知名度不太行，没解除fork关系之前在github都搜索不到，这个项目我也是偶尔从某个地方看到的

**Comment by wilinz** [comment]
我好像是在vscode搜索插件时看到autox.js的插件才找到这个项目的

**Comment by wangwang-code** [comment]
> 我好像是在vscode搜索插件时看到autox.js的插件才找到这个项目的

我最早在一个TG群里看到AutoX内置OCR了

**Comment by wangwang-code** [comment]
@LZX284 仍然是，首次打开不闪退，第二次就闪退

**Comment by wangwang-code** [comment]
https://blog.csdn.net/qq_15110681/article/details/116699909 不知道这篇里的操作可不可行

**Comment by ghost** [comment]
> https://blog.csdn.net/qq_15110681/article/details/116699909 不知道这篇里的操作可不可行

@wangwang-code 报错还是一样的吗？ 看来这次适配尝试失败，再次把 target 值改到 28 或 26 看看吧

**Comment by wangwang-code** [comment]
> > https://blog.csdn.net/qq_15110681/article/details/116699909 不知道这篇里的操作可不可行
> 
> @wangwang-code 报错还是一样的吗？ 看来这次适配尝试失败，再次把 target 值改到 28 或 26 看看吧

对，因为谷歌限制获取设备唯一标识符了

**Comment by ghost** [comment]
> 首先是知名度不太行，没解除fork关系之前在github都搜索不到，这个项目我也是偶尔从某个地方看到的

@wilinz 不仅仅是知名度吧。关键是 AutoX 的定位。你觉得大多数用户使用AutoX的理由是什么？

**Comment by LZX284** [comment]
> 我好像是在vscode搜索插件时看到autox.js的插件才找到这个项目的

你应该也看出来，AutoX 作者自己现在对这个项目也是相当的，那个，态度不积极吧。看一下commit记录，作者自己已经很久没为这个项目贡献过一句代码了，除了日常用手机看看消息合并一下PR，甚至懒惰到连改个版本号也是很不愿意的。这些感觉也可能和AutoX目前的定位有关吧……

**Comment by LZX284** [comment]
> 其实，我就是从hamibot转过来的，至于原因嘛…

相比于同类APP，AutoX 论功能总体上不如pro，论用户活跃度、论脚本丰富也比不上hamibot，那AutoX最大的优势是什么呢？

**Comment by wangwang-code** [comment]
> > 其实，我就是从hamibot转过来的，至于原因嘛…
> 
> 相比于同类APP，AutoX 论功能总体上不如pro，论用户活跃度、论脚本丰富也比不上hamibot，那AutoX最大的优势是什么呢？

恐怕我自己也不知道

**Comment by ghost** [comment]
> 恐怕我自己也不知道

其实OCR功能很多同类APP都有，如果真的有什么优势，那或许就是功能还可以而且还完全免费。pro是App收费，hamibot是脚本和部分功能收费。如果AutoX现在也开始收费，那你还会继续使用AutoX吗？

**Comment by wangwang-code** [comment]
> > 恐怕我自己也不知道
> 
> 其实OCR功能很多同类APP都有，如果真的有什么优势，那或许就是功能还可以而且还完全免费。pro是App收费，hamibot是脚本和部分功能收费。如果AutoX现在也开始收费，那你还会继续使用AutoX吗？

免费的，才是最贵的，与其免费，我更希望它收费

不用hamibot那是我厌恶它，而pro我已经表明过立场了，只要我有办法支付，那我就立刻转移过去

**Comment by ghost** [comment]
> 首先是知名度不太行，没解除fork关系之前在github都搜索不到，这个项目我也是偶尔从某个地方看到的

@wilinz  想要提高知名度，可以看看这个：[有交流群吗，微信或者qq](http://www.autoxjs.com/topic/117/%E6%9C%89%E4%BA%A4%E6%B5%81%E7%BE%A4%E5%90%97-%E5%BE%AE%E4%BF%A1%E6%88%96%E8%80%85qq)。
AutoX 目前就只有一个开发者交流qq群（895775483），不过感觉作者自己似乎也不太积极。如果现在能建立一个面向用户的沟通渠道就好了。

**Comment by wangwang-code** [comment]
> > 首先是知名度不太行，没解除fork关系之前在github都搜索不到，这个项目我也是偶尔从某个地方看到的
> 
> @wilinz 想要提高知名度，可以看看这个：[有交流群吗，微信或者qq](http://www.autoxjs.com/topic/117/%E6%9C%89%E4%BA%A4%E6%B5%81%E7%BE%A4%E5%90%97-%E5%BE%AE%E4%BF%A1%E6%88%96%E8%80%85qq)。 AutoX 目前就只有一个开发者交流qq群（895775483），不过感觉作者自己似乎也不太积极。如果现在能建立一个面向用户的沟通渠道就好了。

其实，TG群会好点，毕竟国内的软件，加上Auto.js的性质…

**Comment by ghost** [comment]
> 不用hamibot那是我厌恶它，而pro我已经表明过立场了，只要我有办法支付，那我就立刻转移过去

像你这样才是正常用户该有的态度，但现状是有很多人其实只想或只能用免费的，而AutoX由于原协议限制，本身其实是根本不可能收费的。
另外，想用pro应该也不难吧。pro有QQ群和官方邮箱，只要加进去问一下，购买就应该不是问题。

**Comment by wangwang-code** [comment]
> > 不用hamibot那是我厌恶它，而pro我已经表明过立场了，只要我有办法支付，那我就立刻转移过去
> 
> 像你这样才是正常用户该有的态度，但现状是有很多人其实只想或只能用免费的，而AutoX由于原协议限制，本身其实是根本不可能收费的。 另外，想用pro应该也不难吧。pro有QQ群和官方邮箱，只要加进去问一下，购买就应该不是问题。

要在谷歌商店里下载，应用里内购

**Comment by LZX284** [comment]
> 其实，TG群会好点，毕竟国内的软件，加上Auto.js的性质…

确实。不过hamibot性质也一样吧，不是照样开微信群了吗。这几种群应该可以都建一个试试吗，多几个沟通渠道也不是坏事。

**Comment by LZX284** [comment]
> 要在谷歌商店里下载，应用里内购

肯定有别的办法，再不行只要你能联系到作者，他一定能帮你处理好的。

**Comment by wangwang-code** [comment]
> > https://blog.csdn.net/qq_15110681/article/details/116699909 不知道这篇里的操作可不可行
> 
> @wangwang-code 报错还是一样的吗？ 看来这次适配尝试失败，再次把 target 值改到 28 或 26 看看吧

28 没用

**Comment by ghost** [comment]
> 28 没用

报错内容是什么？

**Comment by ghost** [comment]
@wangwang-code  PRO 能用的话记得说一声，这边就不用再折腾这个项目了

**Comment by wangwang-code** [comment]
> @wangwang-code PRO 能用的话记得说一声，这边就不用再折腾这个项目了

能用pro我都毕业了



> > 28 没用
> 
> 报错内容是什么？
同上

**Comment by ghost** [comment]
> > 同上

这边用Anderson11的机子测试了一下没发现问题，连接方式是usb网络共享。不知道你那边系统和连接方式是什么？

**Comment by wangwang-code** [comment]
> > > 同上
> 
> 这边用Anderson11的机子测试了一下没发现问题，连接方式是usb网络共享。不知道你那边系统和连接方式是什么？

开关一打开直接闪

**Comment by wangwang-code** [comment]
> > > > 同上
> > 
> > 
> > 这边用Anderson11的机子测试了一下没发现问题，连接方式是usb网络共享。不知道你那边系统和连接方式是什么？
> 
> 开关一打开直接闪

虚拟机倒没问题，

**Comment by ghost** [comment]
> 开关一打开直接闪

也是USB连接，用的vscode autoxjs 的插件吗？开关是 autox 连接电脑那个？

**Comment by wangwang-code** [comment]
> > 开关一打开直接闪
> 
> 也是USB连接，用的vscode autoxjs 的插件吗？开关是 autox 连接电脑那个？

开个就是连接电脑的那个，根本就没连上地址直接填127.0.0.1 正常会报Failed

**Comment by ghost** [comment]
> 开个就是连接电脑的那个，根本就没连上地址直接填127.0.0.1 正常会报Failed

试了一下，填错误的地址确实会报Failed，没异常，要不就是特定机型的兼容性问题。
这是测试链接(为节省时间就没有加入打包功能)：[AutoX-arm64-v8a-test(回退所有升级)](https://github.com/LZX284/AutoX/releases/tag/test)

**Comment by wangwang-code** [comment]
> > 开个就是连接电脑的那个，根本就没连上地址直接填127.0.0.1 正常会报Failed
> 
> 试了一下，填错误的地址确实会报Failed，没异常，要不就是特定机型的兼容性问题。 这是测试链接(为节省时间就没有加入打包功能)：[AutoX-arm64-v8a-test(回退所有升级)](https://github.com/LZX284/AutoX/releases/tag/test)

一切太平

**Comment by ghost** [comment]
> 一切太平

没想到升级java版本也会导致个别机型出现连接问题

**Comment by wangwang-code** [comment]
> > 一切太平
> 
> 没想到升级java版本也会导致个别机型出现连接问题

乖乖用java8，稳定和性能不可兼得
