### ISSUE TITLE
关于OCR

### ISSUE THREAD

**Issue by wangwang-code** [wangwang-code/AutoX#14]

**Comment by LZX284** [comment]
@wangwang-code  好了，现在可以讨论OCR有关的话题了。上一个issue现在也i可以关闭了。

**Comment by ghost** [comment]
@wangwang-code 更新了一下OCR的两个模型，看看效果如何

**Comment by wangwang-code** [comment]
> @wangwang-code 更新了一下OCR的两个模型，看看效果如何

轻量的比标准的，纯文本上，轻量的380ms 标准的420ms，完整上，轻量的577ms，标准的657ms

**Comment by ghost** [comment]
> 轻量的比标准的，纯文本上，轻量的380ms 标准的420ms，完整上，轻量的577ms，标准的657ms

@wangwang-code  实战准确率有没有提高一些？如果识别用时差不多，那还不如都改用标准版，准确率上更有保证

**Comment by wangwang-code** [comment]
> > 轻量的比标准的，纯文本上，轻量的380ms 标准的420ms，完整上，轻量的577ms，标准的657ms
> 
> @wangwang-code 实战准确率有没有提高一些？如果识别用时差不多，那还不如都改用标准版，准确率上更有保证

不清楚，目前我在训练我自己的模型

**Comment by wangwang-code** [comment]
> > 轻量的比标准的，纯文本上，轻量的380ms 标准的420ms，完整上，轻量的577ms，标准的657ms
> 
> @wangwang-code 实战准确率有没有提高一些？如果识别用时差不多，那还不如都改用标准版，准确率上更有保证

不如用之前的，准确率没觉得提高，反而底了点，耗时也加了300ms左右

**Comment by wangwang-code** [comment]
> 不清楚，目前我在训练我自己的模型

我准备训练个水平文本识别的，即识别手机里浏览小说文字等等的，并且能识别出音标和一些生僻字（不强求

**Comment by ghost** [comment]
> 不如用之前的，准确率没觉得提高，反而底了点，耗时也加了300ms左右

可能和使用场景也有关系，针对特定需求，还是用自己训练的模型好，适用性更强。

**Comment by wangwang-code** [comment]
> > 不如用之前的，准确率没觉得提高，反而底了点，耗时也加了300ms左右
> 
> 可能和使用场景也有关系，针对特定需求，还是用自己训练的模型好，适用性更强。

妈妈米哦，弄了半天终于把一个用来测试练手的rec模型弄了出来，就差把它转成.nb的了，饭都没吃

**Comment by ghost** [comment]
太恶心人了，实在不想再与这个项目有任何的关系
AutoX 作者这是把我们这些尽心支持这个项目的用户和贡献者当成什么了？
就这样吧，实在不行还可以去用 [Auto.js M](https://github.com/TonyJiangWJ/Auto.js)

**Comment by wangwang-code** [comment]
> 太恶心人了，实在不想再与这个项目有任何的关系 [AutoX 作者这是把我们这些尽力支持这个项目的用户和贡献者当成什么了？](https://github.com/kkevsekk1/AutoX/issues/345) 就这样吧，实在不行还可以去用 [Auto.js M](https://github.com/TonyJiangWJ/Auto.js)


![在这里插入图片描述](https://img-blog.csdnimg.cn/img_convert/d14b5725b7463db01c17a677bdfc06d8.png#pic_center)

[Auto.js M](https://github.com/TonyJiangWJ/Auto.js)
没有打包功能就算了的，pro我会找些办法试试

**Comment by ghost** [comment]
> [Auto.js M](https://github.com/TonyJiangWJ/Auto.js) 没有打包功能就算了的，pro我会找些办法试试

@wangwang-code  pro不是有一些使用上的问题吗？没有打包功能对你来说也很不方便吧……算了，需要的话就继续用吧。当时对这个项目也倾注了很多精力，也就对这个项目多了几分关注。但AutoX作者现在这个态度，这也实在是让人无法接受的……

**Comment by wangwang-code** [comment]
> @wangwang-code pro不是有一些使用上的问题吗？

对于pro8 有破解限制的代码

> 没有打包功能对你来说也很不方便吧……算了，那就继续用吧。

哪怕一个大大的运行按钮摆在面前，也有人不会用

> 当时对这个项目也倾注了很多精力，也就对这个项目多了几分关注。但AutoX作者现在这个态度，这也实在是让人无法接受的……

一个宏大的项目不是一个人能完成的，我写的脚本，某种意义上讲，叫改，这个脚本已经传了三个人了，我是第三位，当然，我毕业后也会撒手，至于会不会有人接，关心这个干嘛，填饱肚子才是正事

**Comment by ghost** [comment]
> 一个宏大的项目不是一个人能完成的，我写的脚本，某种意义上讲，叫改，这个脚本已经传了三个人了，我是第三位，当然，我毕业后也会撒手，至于会不会有人接，关心这个干嘛，填饱肚子才是正事

开源软件最大的优势不就是能聚集众人的力量共同维护和完善好一个项目吗？但就目前这个状况，参与贡献的开发者不仅完全没有什么保障，有的甚至连应有的尊重也得不到。是啊，那还关心那么多干嘛？反倒还可能害了自己。还是管好自己的正事最重要

**Comment by wangwang-code** [comment]
折腾了一天，就 弄出个 rec.nb 4MB 你说我图啥

**Comment by ghost** [comment]
> 折腾了一天，就 弄出个 rec.nb 4MB 你说我图啥

这个其实是专业问题，人工智能这一块算是比较有难度的，如果不是以后打算从事相关行业，那一般够用就好，否则有时可能白费很多精力还一无所得（尤其是在无人指导的情况下）

**Comment by wangwang-code** [comment]
> > 折腾了一天，就 弄出个 rec.nb 4MB 你说我图啥
> 
> 这个其实是专业问题，人工智能这一块算是比较有难度的，如果不是以后打算从事相关行业，那一般够用就好，否则有时可能白费很多精力还一无所得（尤其是在无人指导的情况下）

对我来说，现在的模型，不够用

**Comment by wangwang-code** [comment]
> > 折腾了一天，就 弄出个 rec.nb 4MB 你说我图啥
> 
> 这个其实是专业问题，人工智能这一块算是比较有难度的，如果不是以后打算从事相关行业，那一般够用就好，否则有时可能白费很多精力还一无所得（尤其是在无人指导的情况下）

最痛苦的是：编译一个opt编译了半天，然后，文档告诉我有现成的...

**Comment by ghost** [comment]
> 对我来说，现在的模型，不够用

有空尝试一下也行，只是要注意不要盲目尝试，动手前多了解一些相关知识，遇到困难时记得寻找帮助。OCR这个，百度应该有开设相关课程吧，也可以去看看学习一下

**Comment by wangwang-code** [comment]
> 有空尝试一下也行，只是要注意不要盲目尝试，动手前多了解一些相关知识，遇到困难时记得寻找帮助。OCR这个，百度应该有开设相关课程吧，也可以去看看学习一下

其实，早有预谋，从2022年的四月底，到现在，一个目标：训练出自己的模型，并应用于实战。现在离完成不远了

**Comment by ghost** [comment]
> 其实，早有预谋，从2022年的四月底，到现在，一个目标：训练出自己的模型，并应用于实战。现在离完成不远了

相当不错了。有机会也要了解一下相关的原理，要不有时出了错都不知道为什么，同时这也有助于你训练出更好的模型。

**Comment by wangwang-code** [comment]
> 相当不错了。有机会也要了解一下相关的原理，要不有时出了错都不知道为什么。

我也只不过是个应用者，对于底层的原理，那不是我要研究的东西（这些东西交给大学生研究生去搞，而我要做的是把它落地）

**Comment by ghost** [comment]
> 我也只不过是个应用者，对于底层的原理，那不是我要研究的东西（这些东西交给大学生研究生去搞，而我要做的是把它落地）

深入研究不现实，只是让你初步了解一下就可以了（程度相当于科普这一类的），这样遇到问题时也好有个方向，知道大概可能是哪一方面出了问题，不至于连该搜索什么都不清楚……

**Comment by wangwang-code** [comment]
> 深入研究不现实，只是让你初步了解一下就可以了，这样遇到问题时也好有个方向，知道大概可能是哪一方面出了问题，不至于连该搜索什么都不清楚……

希望有点的过高了

**Comment by ghost** [comment]
> 希望有点的过高了

@wangwang-code  不难的，相当于科普这一类的程度就行了

**Comment by wangwang-code** [comment]
目前来看，训练出问题了，不识别ABCD这些英文字母了

**Comment by ghost** [comment]
> 目前来看，训练出问题了，不识别ABCD这些英文字母了

那你有办法处理吗？或者，你知道是哪里出了问题吗？文档上有没有相关说明？

**Comment by wangwang-code** [comment]
> 那你有办法处理吗？或者，你知道是哪里出了问题吗？文档上有没有相关说明？

预训练模型==啥也没有，另外，配置文件也弄错了

**Comment by wangwang-code** [comment]
> 预训练模型==啥也没有，另外，配置文件也弄错了

这是我自己的理解，反正我训练出来的模型，它只能识别出我喂给它的数据，其他的就识别不出

比如： 我喂给它一个字 "汪" 那它只能识别出一个 "汪" 字，哪怕识别的图片里没有 “汪” 字

**Comment by ghost** [comment]
> 预训练模型==啥也没有，另外，配置文件也弄错了

做好准备工作很重要的，否则容易犯低级错误

**Comment by wangwang-code** [comment]
自己用预训练模型 训练出来的模型具有很强的针对性
另外，这是一次尝试，至于给它喂一大堆的数据，那我的设备是不行的
后续的训练得靠谷歌[Colab](https://colab.research.google.com/)的免费GPU了

> 做好准备工作很重要的，否则容易犯低级错误

**Comment by wangwang-code** [comment]
简单的讲，这是一次以学习和了解为目的的实践

**Comment by wangwang-code** [comment]
@LZX284 
经过一周的观测和在不同设备上适配，目前发现个问题
一旦离开AutoX打包好的应用，在其他应用上进行OCR速度就变得奇慢无比，甚至在我的手机上也出现这个问题了
只有OCR变得很慢，缩放图片耗时都可以忽略不计

已经开启自启动、丢进游戏盒子、允许高耗能等等的

**Comment by ghost** [comment]
> @LZX284 经过一周的观测和在不同设备上适配，目前发现个问题 一旦离开AutoX打包好的应用，在其他应用上进行OCR速度就变得奇慢无比，甚至在我的手机上也出现这个问题了 只有OCR变得很慢，缩放图片耗时都可以忽略不计
> 
> 已经开启自启动、丢进游戏盒子、允许高耗能等等的

@wangwang-code 你现在还在用 AutoX 吗？ Google paly版的 auto.JS PRO 现在应该可以用支付宝或微信支付了。
另外，最近这边也发生了很多事，实在是没有精力去处理这个项目的问题,,，抱歉了

**Comment by wangwang-code** [comment]
> > @LZX284 经过一周的观测和在不同设备上适配，目前发现个问题 一旦离开AutoX打包好的应用，在其他应用上进行OCR速度就变得奇慢无比，甚至在我的手机上也出现这个问题了 只有OCR变得很慢，缩放图片耗时都可以忽略不计
> > 已经开启自启动、丢进游戏盒子、允许高耗能等等的
> 
> @wangwang-code 你现在还在用 AutoX 吗？ Google paly版的 auto.JS PRO 现在应该可以用支付宝或微信支付了。 另外，最近这边也发生了很多事，实在是没有精力去处理这个项目的问题,,，抱歉了

仍然不支持
另外，尝试用`java.lang.Thread`创建子线程
在子线程里运行OCR识别可以缓解，但仍然很慢，考虑把校验去掉看看

**Comment by ghost** [comment]
> 仍然不支持 另外，尝试用`java.lang.Thread`创建子线程 在子线程里运行OCR识别可以缓解，但仍然很慢，考虑把校验去掉看看

@wangwang-code 顺便升级到V3版模型的OCR如何？

**Comment by wangwang-code** [comment]
> > 仍然不支持 另外，尝试用`java.lang.Thread`创建子线程 在子线程里运行OCR识别可以缓解，但仍然很慢，考虑把校验去掉看看
> 
> @wangwang-code 顺便升级到V3版模型的OCR如何？

v3的效果我已经看过了，不行

**Comment by ghost** [comment]
> v3的效果我已经看过了，不行

那不打包，直接主程序运行OCR不行吗？

**Comment by wangwang-code** [comment]
> > v3的效果我已经看过了，不行
> 
> 那不打包，直接主程序运行OCR不行吗？

https://github.com/TonyJiangWJ/Auto.js/releases/tag/v4.1.22.0621.alpha
试过了，文字检测不行

**Comment by ghost** [comment]
> > 那不打包，直接主程序运行OCR不行吗？
> 
> https://github.com/TonyJiangWJ/Auto.js/releases/tag/v4.1.22.0621.alpha 试过了，文字检测不行

AutoX的也不行吗？

**Comment by wangwang-code** [comment]
> > > 那不打包，直接主程序运行OCR不行吗？
> > 
> > 
> > https://github.com/TonyJiangWJ/Auto.js/releases/tag/v4.1.22.0621.alpha 试过了，文字检测不行
> 
> AutoX的也不行吗？

https://github.com/wangwang-code/AutoX ? 就是后台运行OCR速度不正常，很慢 （V2）

**Comment by ghost** [comment]
> https://github.com/wangwang-code/AutoX ? 就是后台运行OCR速度不正常，很慢 （V2）

@wangwang-code 不知道你现在有空测试吗？如果有的话，这边打算去掉OCR校验、rhino1.7.13及TBS等一系列有潜在隐患的组件，你也顺便可以把Readme修正一下，如何？

**Comment by wangwang-code** [comment]
> > https://github.com/wangwang-code/AutoX ? 就是后台运行OCR速度不正常，很慢 （V2）
> 
> @wangwang-code 不知道你现在有空测试吗？如果有的话，这边打算去掉OCR校验、rhino1.7.13及TBS等一系列有潜在隐患的组件，你也顺便可以把Readme修正一下，如何？

有，暑假闲置在家

**Comment by wangwang-code** [comment]
还发现有些不可点击的控件是能click()点击的，但有概率点击无反应（无论失败与否

**Comment by ghost** [comment]
> 有，暑假闲置在家

稍等。
顺便提一个建议，现在这个项目算是以你为主的吧。这边也主要是不想与AutoX那边的关系搞得太僵，因为只有这样以后他们有代码改进时你才可以顺利拉取他们的代码(防止某些人在你拉取上游代码时设置障碍)，而他们如果需要用到这边的代码的话，只要经过你的同意也可以自由引用，同时你也有权把赞助码放到AutoX里，不知道你觉得如何？

**Comment by wangwang-code** [comment]
> > 有，暑假闲置在家
> 
> 稍等。 顺便提一个建议，现在这个项目算是以你为主的吧。这边也主要是不想与AutoX那边的关系搞得太僵，因为只有这样以后他们有代码改进时你才可以顺利拉取他们的代码(防止某些人在你拉取上游代码时设置障碍)，而他们如果需要用到这边的代码的话，只要经过你的同意也可以自由引用，同时你也有权把赞助码放到AutoX里，不知道你觉得如何？

这只是个满足个人需要的分支项目，比如我不想要控制台的输入框，那我就改xml砍掉它，没有别的

**Comment by ghost** [comment]
> 这只是个满足个人需要的分支项目，比如我不想要控制台的输入框，那我就改xml砍掉它，没有别的

@wangwang-code 那也行吧。这边把相关代码的处理都全部授权给你，以后如果你发现有这个需要时，也可以随时尝试使用这个建议。

**Comment by ghost** [comment]
@wangwang-code 5.X(dev)分支中的 Rhino 1.7.13处理起来有些麻烦，而且这个分支也落后不少了，没什么继续维护的价值，建议没有什么特殊需求的话，可以直接删除这个分支，这样也就不存在因为Rhino 1.7.13而违反开源协议的问题了

**Comment by wangwang-code** [comment]
rm

**Comment by wangwang-code** [comment]
@LZX284 注意更新了，记得pull

**Comment by ghost** [comment]
> @LZX284 注意更新了，记得pull

已经出问题了。只能手动调整一下了

**Comment by wangwang-code** [comment]
> > @LZX284 注意更新了，记得pull
> 
> 已经出问题了。只能手动调整一下了

啥问题

**Comment by ghost** [comment]
> 啥问题

合并冲突，这边网速又不行，看来得等一会了……

**Comment by ghost** [comment]
> 啥问题

@wangwang-code 
好了，试试吧：[AutoX-arm64-v8a(test-去除不规范组件)](https://github.com/LZX284/AutoX/releases/tag/test(%E5%8E%BB%E9%99%A4%E4%B8%8D%E8%A7%84%E8%8C%83%E7%BB%84%E4%BB%B6))

**Comment by wangwang-code** [comment]
> @wangwang-code 好了，试试吧：[AutoX-arm64-v8a(test-去除不规范组件)](https://github.com/LZX284/AutoX/releases/tag/test(%E5%8E%BB%E9%99%A4%E4%B8%8D%E8%A7%84%E8%8C%83%E7%BB%84%E4%BB%B6))

把全屏的按钮删了，另外，如果在运行OCR的一瞬间回到桌面，就会非常缓慢(700->15533ms)

**Comment by ghost** [comment]
> 把全屏的按钮删了，另外，如果在运行OCR的一瞬间回到桌面，就会非常缓慢(700->15533ms)

@wangwang-code 好了，PR提交了，看看行不行
如果没有其它问题的话，这个项目就这样吧，实在是心累，再也不想去掺和与 AutoX 有关的一切了……

**Comment by wangwang-code** [comment]
@LZX284 少依赖了

**Comment by ghost** [comment]
> @LZX284 少依赖了

什么依赖？

**Comment by wangwang-code** [comment]
> > @LZX284 少依赖了
> 
> 什么依赖？

少了6个

**Comment by wangwang-code** [comment]
![Screenshot_20220713_093409](https://user-images.githubusercontent.com/64469117/178629487-f0d6fa4f-315a-4a4e-ad7c-25bd57c5658d.jpg)

**Comment by ghost** [comment]
> 少了6个

@wangwang-code  补充进去了。另外，不知道如果你把这个项目转为private的话，这边还能不能使用合作者的功能？

**Comment by wangwang-code** [comment]
![Screenshot_20220713_102120](https://user-images.githubusercontent.com/64469117/178637191-26661c8c-c2e7-429e-bd3d-2f936a67b306.jpg)
还是少，更奇怪了

**Comment by ghost** [comment]
> 还是少，更奇怪了

@wangwang-code 这次没问题的话，可以发布一个6.2.0版的吧

**Comment by wangwang-code** [comment]
@LZX284 不过编译，出现两个一样的so，不知道该用哪个

```
   > 2 files found with path 'lib/arm64-v8a/libjackpal-androidterm5.so' from inputs:
      - /home/runner/work/AutoX/AutoX/autojs/build/intermediates/library_jni/release/jni/arm64-v8a/libjackpal-androidterm5.so
      - /home/runner/work/AutoX/AutoX/LocalRepo/libtermexec/build/.transforms/2694d8fa060272e52ba2f775ad46da81/transformed/jetified-libtermexec-release/jni/arm64-v8a/libjackpal-androidterm5.so
     If you are using jniLibs and CMake IMPORTED targets, see
```

**Comment by ghost** [comment]
> @LZX284 不过编译，出现两个一样的so，不知道该用哪个

@wangwang-code 这次应该可以了
另外，不知道你打算一直公开参与 AutoX 的维护吗？（因为只要你公开分享，别人就可以拿你的项目用于各种正当或不正当的利益）
如果不是的话则可以避免GPL2协议限制，可以尝试在项目中加入更多的功能，也可以避免卷入到类似的是非中，毕竟很多人参与这个项目也都只是由于它能带来黑灰产或类似这一类的利益

**Comment by wangwang-code** [comment]
> @wangwang-code 这次应该可以了 另外，不知道你打算一直公开参与 AutoX 的维护吗？如果不是的话则可以避免GPL2协议限制，可以尝试在项目中加入更多的功能，也可以避免卷入到类似的是非中，毕竟很多人参与这个项目也都只是由于它能带来黑灰产或类似这一类的利益

维护一词错了，我是有个性的使用者

`For security reasons, you cannot change the visibility of a fork.`

**Comment by ghost** [comment]
> 维护一词错了，我是有个性的使用者
> 
> `For security reasons, you cannot change the visibility of a fork.`

@wangwang-code 出于个人目的使用的话，那也就不用在乎Github上Star数量多少，可以备份一下，再删除当前Fork并重新上传，可以设为Private，也可以换个有个性的名字

**Comment by wangwang-code** [comment]
> @wangwang-code 出于个人目的使用的话，那也就不用在乎Github上Star数量多少，可以备份一下，再删除当前Fork并重新上传，可以设为Private，也可以换个有个性的名字

删库跑路（划掉

**Comment by ghost** [comment]
> 删库跑路（划掉

这个库其实也可以保留，只要另外再新建一个私人仓库就可以了 @wangwang-code

**Comment by ghost** [comment]
> > 删库跑路（划掉
> 
> 这个库其实也可以保留，只要另外再新建一个私人仓库就可以了 @wangwang-code

@wangwang-code 至少公开的维护这边是绝不打算再做了，这边有问题的话也可以选择回退到上一个正确的版本吧，反正也不是不能用……

**Comment by wangwang-code** [comment]
> 这边有问题的话也可以选择回退到上一个正确的版本吧，反正也不是不能用……

已经可以了

**Comment by ghost** [comment]
@wangwang-code PaddleOCR可以升级到2.5版了，并且可以沿用原来V2版的模型
另外还有一件事需要询问你的意见，在APP中加入一个类似精选脚本“的页面，可以用来放你做的脚本项目地址，也可以把Github上一些好的脚本项目的链接放进去。

**Comment by ghost** [comment]
初步想法是有点类似脚本市场的，不同的是这个本身不收集脚本，只提供Github或其它平台上脚本项目的地址，脚本作者可以在自己项目中放上捐赠链接或转账方式等，以便用户可以为自己喜欢的项目提供支持。
不过上游原来是有一个脚本商店页面的，现在经过 @wilinz 的UI重构后已经看不到了，不知道 @wilinz 以及上游那边对这个想法会不会支持？因为觉得同作为社区的维护者，大家其实能一起合作的话才更加有利

**Comment by wangwang-code** [comment]
> 初步想法是有点类似脚本市场的，不同的是这个本身不收集脚本，只提供Github或其它平台上脚本项目的地址，脚本作者可以在自己项目中放上捐赠链接或转账方式等，以便用户可以为自己喜欢的项目提供支持。 不过上游原来是有一个脚本商店页面的，现在经过 @wilinz 的UI重构后已经看不到了，不知道 @wilinz 以及上游那边对这个想法会不会支持？因为觉得同作为社区的维护者，大家其实能一起合作的话才更加有利

不考虑，现在的人，主页面大大写着“开始运行”都看不见，别提其他的了
加上我AutoX只是用来打包程序和调试的

**Comment by ghost** [comment]
> 不考虑，现在的人，主页面大大写着“开始运行”都看不见，别提其他的了 加上我AutoX只是用来打包程序和调试的

也有可能用户是纯小白，对这方面一窍不通的呢。增加脚本页面主要是方便推广和用户反馈，Auto.js用途很多，但开发者也很难所有脚本都自己开发，所以，脚本共享应该是一个值得尝试的想法

**Comment by ghost** [comment]
@wangwang-code 抱歉，是上游的事让你为难了吗？对不起，也是个人对这个项目过多期待了，也才会幻想上游那边可能会和我们合作……
另外，这次更新了OpenCV到4.6.0；PaddleOCR到2.5.0(兼容V2版模型)，不知道你想不想测试一下？ @wangwang-code

**Comment by wangwang-code** [comment]
> @wangwang-code 抱歉，是上游的事让你为难了吗？对不起，也是个人对这个项目过多期待了，也才会幻想上游那边可能会和我们合作…… 另外，这次更新了OpenCV到4.6.0；PaddleOCR到2.5.0(兼容V2版模型)，不知道你想不想测试一下？ @wangwang-code

assets里多出images，能删就删掉

改包名后打包出来的应用图标没了（安装的时候），成安卓默认的了

**Comment by wangwang-code** [comment]
> > @wangwang-code 抱歉，是上游的事让你为难了吗？对不起，也是个人对这个项目过多期待了，也才会幻想上游那边可能会和我们合作…… 另外，这次更新了OpenCV到4.6.0；PaddleOCR到2.5.0(兼容V2版模型)，不知道你想不想测试一下？ @wangwang-code
> 
> assets里多出images，能删就删掉
> 
> 改包名后打包出来的应用图标没了（安装的时候），成安卓默认的了

新的模型感觉耗时变小了

**Comment by wangwang-code** [comment]
@LZX284 主要的问题是打包的应用图标没了

**Comment by ghost** [comment]
> 新的模型感觉耗时变小了

@wangwang-code 嗯，2.4版算法落后，2.5版速度和精确度都略有提升，而再往后的版本就只能用V3版模型（体积为V2版的两倍，速度更慢了），所以现在这版应该就是最优解了

**Comment by ghost** [comment]
> @LZX284 主要的问题是打包的应用图标没了

@wangwang-code 你看看是不是打包后apk的资源文件中缺少相应的图标？

**Comment by wangwang-code** [comment]
> > @LZX284 主要的问题是打包的应用图标没了
> 
> @wangwang-code 你看看是不是打包后apk的资源文件中缺少相应的图标？

没有 inrt res里图标变了

**Comment by ghost** [comment]
> 没有 inrt res里图标变了

@wangwang-code   inrt res mipmap文件夹里的 ic_launcher.png 等图标都没了

**Comment by LZX284** [comment]
> 没有 inrt res里图标变了

@wangwang-code 默认的启动图标似乎是从编译inrt的apk时就已经丢失了，这个暂时没有找到原因……

**Comment by wangwang-code** [comment]
> > 没有 inrt res里图标变了
> 
> @wangwang-code 默认的启动图标似乎是从编译inrt的apk时就已经丢失了，这个暂时没有找到原因……

没有丢

**Comment by ghost** [comment]
> 没有丢

@wangwang-code 你找到默认图标的位置了吗？这边尝试编译的inrt apk里似乎没看到

**Comment by wangwang-code** [comment]
> > 没有丢
> 
> @wangwang-code 你找到默认图标的位置了吗？这边尝试编译的inrt apk里似乎没看到

![image](https://user-images.githubusercontent.com/64469117/180592840-1d272d2c-69dd-4136-8941-5adfa4161be2.png)

aar的锅，删掉不必要的再封装成aar

**Comment by ghost** [comment]
> aar的锅，删掉不必要的再封装成aar

@wangwang-code 不错啊。这次应该可以了，你试试

**Comment by wangwang-code** [comment]
> > aar的锅，删掉不必要的再封装成aar
> 
> @wangwang-code 不错啊。这次应该可以了，你试试

图标没问题了，但apk大小，你不觉得变大很多

**Comment by ghost** [comment]
> 图标没问题了，但apk大小，你不觉得变大很多

变大一点没关系吧？封装还是有封装的优势的。况且这次也更新了不少东西，AAR里能删的都已经删除了，另外一个影响apk的体积的可能是aar包用的是debug版，带有调试信息，这也是为了以后出错的时候比较容易发现问题所在

**Comment by wangwang-code** [comment]
> > 图标没问题了，但apk大小，你不觉得变大很多
> 
> 变大一点没关系吧？封装还是有封装的优势的。况且这次也更新了不少东西，AAR里能删的都已经删除了，另外一个影响apk的体积的可能是aar包用的是debug版，带有调试信息，这也是为了以后出错的时候比较容易发现问题所在

OCR校验看看能不能删

**Comment by ghost** [comment]
> OCR校验看看能不能删

@wangwang-code 删过了。不过这次在测试打包OCR的稳定性时发现最初一两次启动容易失败，不得已又把OCR校验又加了回去

**Comment by ghost** [comment]
@wangwang-code 这次更新差不多了。你看看如果没有其它问题的话就可以发布一个新版了，另外这个Issue应该也可以关闭了。

**Comment by ghost** [comment]
@wangwang-code 没有出现什么异常吧？没有的话那这个Issue就可以关闭了吧？
