### ISSUE TITLE
调小连接电脑的超时

### ISSUE THREAD

**Issue by wangwang-code** [wangwang-code/AutoX#17]
手一抖，很好，得等一会才能超时重填

**Comment by ghost** [comment]
重启APP试试，这样应该就不用等待了

**Comment by wangwang-code** [comment]
> 重启APP试试，这样应该就不用等待了

就不能改下超时时间吗，重启app也得等待

**Comment by ghost** [comment]
> 就不能改下超时时间吗，重启app也得等待

就怕改了会引起其它问题，比如可能导致网络不佳时连接总是失败

**Comment by ghost** [comment]
@wangwang-code  6.1.8_10 尝试升级到28  测试成功了吗？

**Comment by wangwang-code** [comment]
> @wangwang-code 6.1.8_10 尝试升级到28 测试成功了吗？

对，没出啥问题

**Comment by ghost** [comment]
@wangwang-code  上次升级到32不是出现了文件存储权限方面的问题吗？
另外，不知道你需不需要TTS功能？

**Comment by wangwang-code** [comment]
> @wangwang-code 上次升级到32不是出现了文件存储权限方面的问题吗？ 另外，不知道你需不需要TTS功能？

可以试试，开issue吧

**Comment by ghost** [comment]
> 可以试试，开issue吧

TTS功能的开源协议是GPL3，也就是需要你先在项目中添加一个GPL3的协议，然后这边PR过去你就可以开始测试了。

**Comment by wangwang-code** [comment]
> > 可以试试，开issue吧
> 
> TTS功能的开源协议是GPL3，也就是需要你先将项目的GPL2协议删除再添加一个GPL3的，然后这边PR过去你就可以开始测试了。

GPL2和GPL3有那些差别

**Comment by LZX284** [comment]
> GPL2和GPL3有那些差别

GPL3算是GPL2的后续升级版吧，具体内容搜索一下就有了。

**Comment by LZX284** [comment]
> GPL2和GPL3有那些差别

@wangwang-code   刚看到一个说GPLV2和GPLV3存在不兼容的，那这样就不能删除GPL2了，而是要在之前基础上再添加一个GPL3的协议。不过这些协议大同小异，对普通用户来说差别也不大

**Comment by ghost** [comment]
> GPL2和GPL3有那些差别

@wangwang-code 不对，除了看到一个说GPLV2和GPLV3存在不兼容的，还看到说不能将这两种协议的代码混在一起的，也就是说 GPL3协议的 TTS 是无法添加进项目里了

**Comment by wangwang-code** [comment]
> > GPL2和GPL3有那些差别
> 
> @wangwang-code 不对，除了看到一个说GPLV2和GPLV3存在不兼容的，还看到说不能将这两种协议的代码混在一起的，也就是说 GPL3协议的 TTS 是无法添加进项目里了

...

**Comment by wangwang-code** [comment]
@LZX284 升级到32的https://github.com/wangwang-code/AutoX/releases/tag/6.1.8_11 一切正常，对读写正常

**Comment by ghost** [comment]
> ...

@wangwang-code  不过你想用也不是没有办法，因为只有公开发布的项目才需要遵守协议，如果是个人私下使用那就不受限制了。但这样的话就无法公开PR到Github上了。

**Comment by wangwang-code** [comment]
> > ...
> 
> @wangwang-code 不过你想用也不是没有办法，因为只有公开发布的代码才需要遵守协议，如果是个人私下使用那就不受限制了。但这样的话就无法公开PR到Github上了。

那没就没必要用TTS，不如加个pro版里的关闭电池优化的功能， https://g.pro.autojs.org/docs/#/zh-cn/powerManager

**Comment by ghost** [comment]
> 那没就没必要用TTS，不如加个pro版里的关闭电池优化的功能， https://g.pro.autojs.org/docs/#/zh-cn/powerManager

@wangwang-code  具体有什么作用吗？感觉这个有可能伤害电池寿命，而且对后台运行帮助也不大

**Comment by wangwang-code** [comment]
> > 那没就没必要用TTS，不如加个pro版里的关闭电池优化的功能， https://g.pro.autojs.org/docs/#/zh-cn/powerManager
> 
> @wangwang-code 具体有什么作用吗？感觉这个有可能伤害电池寿命，而且对后台运行帮助也不大

（心里安慰）反正就是用来防止系统报高功耗（（（

**Comment by ghost** [comment]
> （心里安慰）反正就是用来防止系统报高功耗（（（

@wangwang-code  这个手动设置也可以吧，开多了伤手机，个别需要的就手动调整吧。与其加这个，不如研究一下其它更加实用的功能吧，比如，数据库

**Comment by wangwang-code** [comment]
> > （心里安慰）反正就是用来防止系统报高功耗（（（
> 
> @wangwang-code 这个手动设置也可以吧，开多了伤手机，个别需要的就手动调整吧。与其加这个，不如研究一下其它更加实用的功能吧，比如，数据库

现在的系统都把这个页面藏起来了，数据库的话，SQL文件还不够用吗

**Comment by ghost** [comment]
> 现在的系统都把这个页面藏起来了，数据库的话，SQL文件还不够用吗

PRO里面有这个API和示例，你看看如果感觉不需要就算了。
另外，升级到32如果没问题的话，那现在就可以发布一个 6.1.9 的版本了。

**Comment by wangwang-code** [comment]
> PRO里面有这个API和示例，你看看如果感觉不需要就算了。

指那个

**Comment by ghost** [comment]
> 指那个

API是在pro的文档里看到的。具体效果如何因为没购买PRO所以也不清楚

**Comment by wangwang-code** [comment]
> > 指那个
> 
> API是在pro的文档里看到的。具体效果如何因为没购买PRO所以也不清楚

是指电池优化 还是 TTS

**Comment by ghost** [comment]
> 是指电池优化 还是 TTS

数据库 sqlite 用JavaScript创建数据库那个

**Comment by wangwang-code** [comment]
> > 是指电池优化 还是 TTS
> 
> 数据库 sqlite 用JavaScript创建数据库那个

没这个需求

**Comment by ghost** [comment]
> 没这个需求

那发布一下新版，这个阶段的维护工作就算完成了
