### ISSUE TITLE
添加个2个与前台服务有关的函数

### ISSUE THREAD

**Issue by wangwang-code** [wangwang-code/AutoX#28]
一个是启动前台服务
一个是停止前台服务

这样打包后脚本执行完了就可以关掉前台服务的通知了

**Comment by wangwang-code** [comment]
@LZX284 这个需求，应该不难，现在init()不会启动前台服务了，AutoX 侧边栏的前台服务也能正常使用了

**Comment by ghost** [comment]
> @LZX284 这个需求，应该不难，现在init()不会启动前台服务了，AutoX 侧边栏的前台服务也能正常使用了

@wangwang-code 不是难不难的问题啊，主要是不想再公开维护了

**Comment by ghost** [comment]
@wangwang-code  上游更新了，这次改的太多了，你想同步的话还是会遇到不少麻烦，只能建议你保存当前版本源码，然后强制同步上游更新，再把自己版本的内容慢慢补充回去(其实也没多少)

**Comment by wangwang-code** [comment]
> @wangwang-code 上游更新了，这次改的太多了，你想同步的话还是会遇到不少麻烦，只能建议你保存当前版本源码，然后强制同步上游更新，再把自己版本的内容慢慢补充回去(其实也没多少)

考虑回滚代码后合并上游更新，再改自己的内容

**Comment by ghost** [comment]
> > @wangwang-code 上游更新了，这次改的太多了，你想同步的话还是会遇到不少麻烦，只能建议你保存当前版本源码，然后强制同步上游更新，再把自己版本的内容慢慢补充回去(其实也没多少)
> 
> 考虑回滚代码后合并上游更新，再改自己的内容

@wangwang-code  可以

**Comment by wangwang-code** [comment]
> > > @wangwang-code 上游更新了，这次改的太多了，你想同步的话还是会遇到不少麻烦，只能建议你保存当前版本源码，然后强制同步上游更新，再把自己版本的内容慢慢补充回去(其实也没多少)
> > 
> > 
> > 考虑回滚代码后合并上游更新，再改自己的内容
> 
> @wangwang-code 可以

回滚并合并上游更新了

**Comment by ghost** [comment]
> 回滚并合并上游更新了

@wangwang-code 好的。那你先改你自己提交的那些以及OCR相关的，其它的比如项目结构那些就先不要动了，有问题再说

**Comment by ghost** [comment]
@wangwang-code 上游更新似乎结束了。不知道你是不是还在写脚本？

**Comment by wangwang-code** [comment]
> @wangwang-code 上游更新似乎结束了。不知道你是不是还在写脚本？

在debug，没啥功能要加了，上游准备弄下OCR

**Comment by ghost** [comment]
> 在debug，没啥功能要加了，上游准备弄下OCR

上游的Q群你加了？OCR似乎也没有啥功能好加了

**Comment by wangwang-code** [comment]
> 上游的Q群你加了？OCR似乎也没有啥功能好加了

主要是有其他人反应最近几个版本OCR的速度有点慢

**Comment by ghost** [comment]
> 主要是有其他人反应最近几个版本OCR的速度有点慢

OCR最完善的版本就是你这版了吧，再想提速只能靠优化模型，C++部分几乎是没法再改进的

**Comment by wangwang-code** [comment]
> OCR最完善的版本就是你这版了吧，再想提速只能靠优化模型，C++部分几乎是没法再改进的

回滚没了

**Comment by LZX284** [comment]
> 回滚没了

旧版有历史记录的啊，而且授权都给你了，你可以自己再补充进去的

**Comment by ghost** [comment]
> 回滚没了

@wangwang-code 上游那边，作者对OCR的有些改动并不好。要不还是把OCR还原回我们自己的版本吧，你先不要改动，以防待会合并冲突

**Comment by wangwang-code** [comment]
> > 回滚没了
> 
> @wangwang-code 上游那边，作者对OCR的有些改动并不好。要不还是把OCR还原回我们自己的版本吧，你先不要改动，以防待会合并冲突

我发现，把OCR源码塞进去，AutoX的大小还能小一点，用aar会大一点（疑惑

**Comment by ghost** [comment]
> 我发现，把OCR源码塞进去，AutoX的大小还能小一点，用aar会大一点（疑惑

@wangwang-code 会。因为aar包含了多个平台的支持库和文件，会比用源码编译的体积稍微大点，不过性能兼容性方面没什么差别

**Comment by ghost** [comment]
@wangwang-code 另外，这次也把更新功能修正回我们自己的项目，你可以改一下版本号，发布一个新版试试行不行

**Comment by ghost** [comment]
@wangwang-code 可以再升级一下版本号，看上一个版本的APP的更新功能是否正常？

**Comment by wangwang-code** [comment]
> @wangwang-code 可以再升级一下版本号，看上一个版本的APP的更新功能是否正常？

集成文档倒不需要

**Comment by ghost** [comment]
> 集成文档倒不需要

@wangwang-code  可能你不需要，但是我这边需要呢？当然，如果你坚持的话，这边也没什么好说的

**Comment by ghost** [comment]
> 集成文档倒不需要

@wangwang-code 另外，集成到项目中也方便离线查看和更新，毕竟，如果每次想要完善文档都必须要到AutoX作者那里提PR等上十几天（有时甚至都会被随意关闭）确实是很不好的体验

**Comment by wangwang-code** [comment]
> @wangwang-code 另外，集成到项目中也方便离线查看和更新，毕竟，如果每次想要完善文档都必须要到AutoX作者那里提PR等上十几天（有时甚至都会被随意关闭）确实是很不好的体验

https://github.com/wangwang-code/kkevsekk1.github.io

**Comment by wangwang-code** [comment]
@LZX284 去除32位应用，编译不过

我也用不到

**Comment by ghost** [comment]
> https://github.com/wangwang-code/kkevsekk1.github.io

@wangwang-code 可以。那就去掉本地文档换成你的，去掉32位，这样可以吗？
另外，更新功能是根据版本号进行判断的，没改版本号的话检测更新可能会出错

**Comment by ghost** [comment]
> https://github.com/wangwang-code/kkevsekk1.github.io

@wangwang-code 遇到点问题，这个GitHub的文档地址似乎不适合直接用webview打开看，而上游也是通过建立网站的方式将其转化为适合查看的格式，感觉有点麻烦

**Comment by wangwang-code** [comment]
> @wangwang-code 遇到点问题，这个GitHub的文档地址似乎不适合直接用webview打开看，而上游也是通过建立网站的方式将其转化为适合查看的格式，感觉有点麻烦

不适合...
https://wangwang-code.github.io/kkevsekk1.github.io/

**Comment by LZX284** [comment]
> 不适合... https://wangwang-code.github.io/kkevsekk1.github.io/

@wangwang-code  这个没怎么用过，还以为上游是另外搭建的网站。
另外，不知道文档那边的项目能不能使用合作者模式？这样以后维护也比较方便

**Comment by LZX284** [comment]
@wangwang-code 其实我发现你还是挺有能力的嘛。如果这两年你还要写脚本，那这个项目也可以一直维护到你不再写为止。
另外，这几天有点空闲了，不知道电池优化和打包的前台服务这两个功能你还需不需要实现？

**Comment by wangwang-code** [comment]
电池优化已经实现了，前台的话我觉得不如不开
```
let powerManager = context.getSystemService(context.POWER_SERVICE),
    isIgnoring = powerManager.isIgnoringBatteryOptimizations(context.getPackageName());

if (!isIgnoring) {
    app.startActivity({
        action: "android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
        data: "package:" + context.getPackageName()
    })
} else {
// 打开电池优化列表
app.startActivity({
    action: "android.settings.IGNORE_BATTERY_OPTIMIZATION_SETTINGS"
})}
```

**Comment by LZX284** [comment]
> 电池优化已经实现了，前台的话我觉得不如不开

也行。那你要是有其它需求就提个Issue，大家讨论一下，能实现的话就帮你解决了

**Comment by wangwang-code** [comment]
没什么需求了，起码现在没有。脚本那边还有一堆未被发现的BUG等着我修呢
