### ISSUE TITLE
能否出一个通过action打包教程？

### ISSUE THREAD

**Issue by codesopen** [wangwang-code/AutoX#36]
我fork项目 通过action打包一直不成功，错误提示如下：
Failed to load signer "signer #1"
java.io.IOException: Short read of DER length
	at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:560)
	at java.base/sun.security.util.DerValue.init(DerValue.java:413)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:355)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:368)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1960)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:220)

**Comment by ghost** [comment]
@alphaerp 看了一下你的action日志：
The process '/usr/local/lib/android/sdk/build-tools/30.0.2/apksigner' failed with exit code 2
这个比较奇怪，因为项目中设置的build-tools版本都是32.0.0，不知道是否云端主机异常的原因，要不你同步一下代码再启动action试试？
另外，这边运行打包的ACTION一般都不会出错，手动触发的正在测试，或者，你也可以选择从这里下载打包好的或本地编译试试

**Comment by ghost** [comment]
@alphaerp 这边手动触发ACTION的结果出来了，结果正常，你可以看一下：[Android CI](https://github.com/wangwang-code/AutoX/actions/runs/2718251734)

**Comment by codesopen** [comment]
@LZX284 感谢你的热心服务，我是forkwangwang-code仓库最新代码。 这是我的[Android CI](https://github.com/alphaerp/AutoX/actions/runs/2717992736)

**Comment by codesopen** [comment]
@LZX284 你有Q群或V群吗？ 方便拉我一下

**Comment by ghost** [comment]
> @LZX284 你有Q群或V群吗？ 方便拉我一下

暂时没有……

**Comment by codesopen** [comment]
@LZX284  手动出发Action，运行dev-test分支，还是之前的问题。

**Comment by ghost** [comment]
> @LZX284 手动出发Action，运行dev-test分支，还是之前的问题。

@alphaerp 测试了一下，这边Fork的分支也出现了这个问题：[Android CI](https://github.com/LZX284/AutoX/actions/runs/2718574100)，目前来看应该是和Github编译设置有关，不过个人对这块也不是很熟悉，暂时没有什么好的办法……

**Comment by codesopen** [comment]
好的，多谢回复

**Comment by wilinz** [comment]
@alphaerp 需要设置签名证书，仓库 -> settings -> secrets ,
signingKeyBase64: linux下运行此命令获得：```openssl base64 < some_signing_key.jks | tr -d '\n' | tee some_signing_key.jks.base64.txt``` some_signing_key.jks是你的证书
![image](https://user-images.githubusercontent.com/59408438/180719520-dab340ca-906e-41d2-9cb6-0900f7c6bd69.png)

**Comment by codesopen** [comment]
@wilinz 感谢回复，另外我下载Android studio, 导入源码=>sync的时候报错提示：Unrecognized Android Studio (or Android Support plugin for IntelliJ IDEA) version '202.7660.26.42.7486908', please retry with version 2021.2.1 or newer.
根据问题网上搜素说我的版本过低，实际我的AS版本就是2021的，一顿乱解决，这个问题不出现，但其他问题出现了。 大佬能否给我一个你们用的AS安装包和环境配置需求，我已经弄了3天，还没搞定。愁死我了。~~呜

**Comment by wilinz** [comment]
官网下载最新版

**Comment by codesopen** [comment]
@wilinz 感谢回复， 下载最新依然未能构建成功，可能还是环境问题我没处理好。
问下大佬，未来有计划往autojsx增加远程投屏在pc端显示的功能吗？

**Comment by wilinz** [comment]
> @wilinz 感谢回复， 下载最新依然未能构建成功，可能还是环境问题我没处理好。 问下大佬，未来有计划往autojsx增加远程投屏在pc端显示的功能吗？

没有，投屏请使用vysor或者rustdesk

**Comment by ghost** [comment]
> 下载最新依然未能构建成功，可能还是环境问题我没处理好。 问下大佬，未来有计划往autojsx增加远程投屏在pc端显示的功能吗？

@alphaerp 还以为你已经解决了呢……
方便的话能不能把你具体的环境配置和源码版本发出来看看？要不很难确定问题到底是在哪里

**Comment by codesopen** [comment]
@LZX284  最近一直在开发服务端， 刚看到有消息所以及时回复一下。

**Comment by codesopen** [comment]
@wilinz  多谢。 这个我了解了一下， 投屏多台不方便集中管理。
