### ISSUE TITLE
6.2.5 中的device.height和device.width出現null

### ISSUE THREAD

**Issue by jeromeleong** [wangwang-code/AutoX#45]
之前的6.2.4版本運行順利, 而wilinz  的Autoxjs 6.2.5也沒有出現這個問題

**Comment by ghost** [comment]
@jeromeleong  尝试修复了一下，看看效果行不行：
[修复：device.和TTS模块中的错误问题](https://github.com/wangwang-code/AutoX/commit/702cbb403da55698e567dcecd089c94cf1820a17)
[Pre-release V6.2.5E](https://github.com/LZX284/Auto.Js/releases)

**Comment by jeromeleong** [comment]
> @jeromeleong 試了一下，看看效果行不通： [修復：device.和TTS模塊中的錯誤問題](https://github.com/wangwang-code/AutoX/commit/702cbb403da55698e567dcecd089c94cf1820a17) [Pre-release V6.2.5E](https://github.com/LZX284/Auto.Js/releases)

device可以用了. 但切換了tbs webview 后, 一打开软件就崩坏

Version: 625
Android: 30
kotlin.UninitializedPropertyAccessException: lateinit property mWebView has not been initialized
org.autojs.autojs.ui.main.web.EWebView$MyWebViewClientTbs.onPageStarted(EWebView.kt:295)
com.tencent.smtt.sdk.SystemWebViewClient.onPageStarted(Unknown Source:9)
bF0.b(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:406)
Wa.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:170)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:257)
android.app.ActivityThread.main(ActivityThread.java:8315)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Comment by ghost** [comment]
> device可以用了. 但切換了tbs webview 后, 一打开软件就崩坏
> 
@jeromeleong 修復了，試試吧：
[V6.2.5E(2022-08-13重新發佈)](https://github.com/LZX284/Auto.Js/releases)
