### ISSUE TITLE
最新版(6.3.6)加入的OpenCC效果不错

### ISSUE THREAD

**Issue by ghost** [wangwang-code/AutoX#52]
用示例代码试了一下，转换成功。

**Comment by ghost** [comment]
@wangwang-code 强制合并后，大部分内容和上游都是一样的，看反馈bug似乎有点多，大多都还是不好修复的那种，不知道你现在用起来感觉怎样？

**Comment by wangwang-code** [comment]
> @wangwang-code 强制合并后，大部分内容和上游都是一样的，看反馈bug似乎有点多，大多都还是不好修复的那种，不知道你现在用起来感觉怎样？

无感，半年后也不再写了

**Comment by ghost** [comment]
> 无感，半年后也不再写了

也好久不用autojs了。起初只是抱着学习的态度，顺便回馈一些自己的改进，谁知道最后会变成现在这个样子？
脚本的话，是因为无障碍和截图功能都被屏蔽了吧？

**Comment by wangwang-code** [comment]
> > 无感，半年后也不再写了
> 
> 也好久不用autojs了。起初只是抱着学习的态度，顺便回馈一些自己的改进，谁知道最后会变成现在这个样子？ 脚本的话，是因为无障碍和截图功能都被屏蔽了吧？

不关注，只知道被审查了

**Comment by ghost** [comment]
> 不关注，只知道被审查了

你写的是不是学习强国相关的脚本？类似这样的确实存在违法嫌疑，不盈利还好，没有什么人管，不过说实话，用AJ的很多都是冲着搞钱的目的去的，如果遇到有人举报，真要追究责任的话也会很麻烦的

**Comment by ghost** [comment]
@wangwang-code 不知道你能不能问你一些关于AutoX群里的事？为什么感觉他们似乎很讨厌我，似乎处处针对我？
我知道自己有些事确实做得不对。开头是不满作者的态度和作者吵了一架，当时情绪是有些失控了。
不过那时真是有点蠢，自从和你另外维护了一个分支版后事情就变得进退两难了，想和解重新合并分支但也不能对不起你，至少也需要你的同意才行，wilinz当时在两边都是合作者，曾想过他能帮忙与作者沟通，但他也不怎么回复我，后来他直接退出了这边的合作，有些话就真的说不下去了。
后来尝试去了群里，想尝试和解，我先是问了和你有关的事，当时出面的是wilinz，但几句话就有点上火气了，谈不下去。当时我以为是wilinz故意针对我，所以后面在github帖子里才会说了些wilinz不好的话。其实我不应该说那些的，可当时作者长期不回复真的很让人心态受不了的。后面的事也真的是一言难尽吧

**Comment by wangwang-code** [comment]
> @wangwang-code 不知道你能不能问你一些关于AutoX群里的事？为什么感觉他们似乎很讨厌我，似乎处处针对我？ 我知道自己有些事确实做得不对。开头是不满作者的态度和作者吵了一架，当时情绪是有些失控了。 不过那时真是有点蠢，自从和你另外维护了一个分支版后事情就变得进退两难了，想和解重新合并分支但也不能对不起你，至少也需要你的同意才行，wilinz当时在两边都是合作者，曾想过他能帮忙与作者沟通，但他也不怎么回复我，后来他直接退出了这边的合作，有些话就真的说不下去了。 后来尝试去了群里，想尝试和解，我先是问了和你有关的事，当时出面的是wilinz，但几句话就有点上火气了，谈不下去。当时我以为是wilinz故意针对我，所以后面在github帖子里才会说了些wilinz不好的话。其实我不应该说那些的，可当时作者长期不回复真的很让人心态受不了的。后面的事也真的是一言难尽吧

我不清楚wilinz有没有曲解我的话，我不想插手你们两的事，但wilinz在群里似乎很讨厌你
你走了之后我倾向于wilinz，mlkt没他现在可用不上
另外我不擅长处理这种事，我也不清楚自己有没有在拱火，不过wilinz目前已经没精力管项目了

过去的东西就让它过去吧，热爱的东西总有一天会无味的

在这里一并说下，我目前靠着捡洋垃圾拼了入门3A的一整套pc，没什么升级下去的想法了，反正比那美帝良心强就是了

**Comment by ghost** [comment]
> 过去的东西就让它过去吧，热爱的东西总有一天会无味的
> 
> 在这里一并说下，我目前靠着捡洋垃圾拼了入门3A的一整套pc，没什么升级下去的想法了，反正比那美帝良心强就是了

我也希望不再管这些了，但当时那种近乎万箭穿心的感受，不是生理上的原因，如果不是中了邪，那也许就是有人恨我彻骨吧。我真的想不通，所以现在也只是想弄清楚而已
另外，会写代码真的很赚钱，记得你说过你靠写脚本赚了一张750显卡，但在pro群里，我见过同样一个高中少年，他靠写代码可是赚了整整一套深度学习的顶级配置，至少几万块吧，你只要好好学习，想要好电脑完全不需要靠捡洋垃圾的

**Comment by wangwang-code** [comment]
> > 过去的东西就让它过去吧，热爱的东西总有一天会无味的
> > 在这里一并说下，我目前靠着捡洋垃圾拼了入门3A的一整套pc，没什么升级下去的想法了，反正比那美帝良心强就是了
> 
> 我也希望不再管这些了，但当时那种近乎万箭穿心的感受，不是生理上的原因，如果不是中了邪，那也许就是有人恨我彻骨吧。我真的想不通，所以现在也只是想弄清楚而已 另外，会写代码真的很赚钱，记得你说过你靠写脚本赚了一张750显卡，但在pro群里，我见过同样一个高中少年，他靠写代码可是赚了整整一套深度学习的顶级配置，至少几万块吧，你只要好好学习，想要好电脑完全不需要靠捡洋垃圾的

一张1060矿卡，虽然英语依托答辩，但数学还是有好过，小时候总认为编程很牛，现在看“你和代码总有一个能跑”“能编译完成润起来就夭寿了”😂

**Comment by ghost** [comment]
> 一张1060矿卡，虽然英语依托答辩，但数学还是有好过，小时候总认为编程很牛，现在看“你和代码总有一个能跑”“能编译完成润起来就夭寿了”😂

加油吧！不知道以后你想考个什么样的专业，不过如果你想要精通编程这一块的话，英语可以差一点，但至少数学绝不能拉胯

**Comment by ghost** [comment]
> 我不清楚wilinz有没有曲解我的话，我不想插手你们两的事，但wilinz在群里似乎很讨厌你 你走了之后我倾向于wilinz，mlkt没他现在可用不上 另外我不擅长处理这种事，我也不清楚自己有没有在拱火，不过wilinz目前已经没精力管项目了

@wangwang-code wilinz讨厌我应该是因为捐赠这件事吧。这事你也知道，开头我看到那个请求捐赠的人可能是他时就直接提了出来，当时是觉得不太合适，不过直接提出来这个做法应该是伤害到他了，后来又转念一想觉得这其实对这个项目有好处，另一方面也许能让作者改变一下态度吧（毕竟总不能收了赞助还对用户需求爱理不理的），就改变态度让你带头支持他了。不过后来因为开源协议的问题，是不是违规这个应该不好判断，但当时自己过于坚持原则了，加上自己有点感觉wilinz在针对自己，才对wilinz说了那些话，不过随后我就后悔了，还提醒他不要搞得太公开就行。也许这会让人误会这都是自己在“挖坑”陷害他。随后作者也把我屏蔽了，事情也开始变得无可挽回。事后想想其实这个也没必要，毕竟这不是我的项目，作者遵不遵守开源协议、围不违规都和自己没关系，就算态度有问题又怎么样，那也是他的自由，贡献者没权利去要求什么的。唉，都是我的不对吧，管这么多干什么。
@wilinz 不知道你能不能看到，群里反正是去不了了，我只能在这里跟你说抱歉了，我也不太擅长处理这种事，之前那么多争论确实也和自己脱不了干系，很对不起，很多事其实都是不应该做的。事情过去的就让它过去，如果你还是不满意，也可以过来骂我一顿也好。

**Comment by ghost** [comment]
@wangwang-code  也许他还是看不到吧。冤家宜解不宜结，如果可以的话，希望你帮忙转达一下自己的歉意吧。

**Comment by wilinz** [comment]
有兴趣的话去维护 [https://github.com/openautojs/openautojs](https://github.com/openautojs/openautojs)

**Comment by wilinz** [comment]
让 kkevsekk1 管理项目的话搞不下去了 艾特半个月不合pr，版本号连续弄错几个版本

**Comment by ghost** [comment]
> 有兴趣的话去维护 https://github.com/openautojs/openautojs

可以。不过还是希望可以处理好和 kkevsekk1 那边的关系吧，避免发生矛盾
