### ISSUE TITLE
Release上面的版本和APP的版本号不匹配，希望能修改一下

### ISSUE THREAD

**Issue by ghost** [wangwang-code/AutoX#8]
如题

**Comment by lnxcyq** [comment]
是啊，你这说是6.1.8，下载安装显示还是6.1.4

**Comment by ghost** [comment]
算了，不改也没关系，就是有些用户可能会产生误会吧…… [AutoX](https://github.com/kkevsekk1/AutoX) 断开了同 [源头项目](https://github.com/hyb1996/Auto.js) 的Fork关系，甚至 wilinzx 还开了要求捐赠的帖子：【作者可以开通github打赏吗】（你没看错， [ixinwiki](https://github.com/ixinwiki) 就是  wilinzx ，名字不一样，差点就信了，但 [Releases6.1.6页面](https://github.com/kkevsekk1/AutoX/releases/tag/6.1.6) 依然显示 [ixinwiki](https://github.com/ixinwiki) 是贡献者……）

![无标题](https://user-images.githubusercontent.com/105829296/174687801-3a9fbe96-9d0e-47f3-aa87-90627051aae9.jpg)

**Comment by ghost** [comment]
不过既然都要开打赏了，那至少得承担起一些维护的责任吧？ @wangwang-code  你希望的 【添加 自定义OCR模型文件夹】 ，或许你给他一些打赏，[wilinz](https://github.com/wilinz) 就会帮你实现了……

**Comment by wangwang-code** [comment]
> 不过既然都要开打赏了，那至少得承担起一些维护的责任吧？ @wangwang-code 你希望的 [添加 自定义OCR模型文件夹](https://github.com/kkevsekk1/AutoX/issues/335) ，或许你给他一些打赏，[wilinz](https://github.com/wilinz) 就会帮你实现了……

可以，写脚本我也捞了点油水（日常坑同学）

**Comment by ghost** [comment]
@wangwang-code  [上游](https://github.com/kkevsekk1/AutoX) 更新了。
[Releases](https://github.com/wangwang-code/AutoX/releases) 打包通用APP虽然可以，但目前 PaddleOCR移动端 缺乏对 x86、x86_64架构的支持，就算打包出来了，在这两个平台上(一般是x86平板或x86模拟器) OCR也不可用，所以不推荐打包时包括这两个架构。

**Comment by wangwang-code** [comment]
> @wangwang-code [上游](https://github.com/kkevsekk1/AutoX) 更新了。 [Releases](https://github.com/wangwang-code/AutoX/releases) 打包通用APP虽然可以，但目前 PaddleOCR移动端 缺乏对 x86、x86_64架构的支持，就算打包出来了，在这两个平台上(一般是x86平板或x86模拟器) OCR也不可用，所以不推荐打包时包括这两个架构。

还增大apk

**Comment by wangwang-code** [comment]
> @wangwang-code [上游](https://github.com/kkevsekk1/AutoX) 更新了。 [Releases](https://github.com/wangwang-code/AutoX/releases) 打包通用APP虽然可以，但目前 PaddleOCR移动端 缺乏对 x86、x86_64架构的支持，就算打包出来了，在这两个平台上(一般是x86平板或x86模拟器) OCR也不可用，所以不推荐打包时包括这两个架构。

分支无法合并，冲突了

**Comment by ghost** [comment]
> 分支无法合并，冲突了

可以手动处理。只合并那些有你想要的功能的文件就行了，其它的就不需要管了。

**Comment by wangwang-code** [comment]
> > 分支无法合并，冲突了
> 
> 可以手动处理。只合并那些有你想要的功能的文件就行了，其它的就不需要管了。

https://github.com/wangwang-code/AutoX/runs/6985518587?check_suite_focus=true 失败了 哎~

**Comment by ghost** [comment]
> https://github.com/wangwang-code/AutoX/runs/6985518587?check_suite_focus=true 失败了 哎~

@wangwang-code 修正了一些编译错误，及补充js文件内容 。
另外，[上游](https://github.com/kkevsekk1/AutoX) 那些破事其实没有必要去管的。作为学生，这个阶段好好学习和提高自己才是正道。有空的话也可以写写脚本赚赚外快，而这个项目本来就是个人自用的一个Fork而已，满足自己的需求也就行了。
